<?php
/**
 * @file
 * Integrates quickpay.dk redirected payment service.
 */

// The protocol version we implement for the payment window.
define('QUICKPAY_VERSION', 'v10');

/**
 * Implements hook_menu().
 */
function quickpay_menu() {
  $items = array();
  $items['quickpay/%'] = array(
    'title' => 'Quickpay callback page',
    'page callback' => '_quickpay_callback',
    'page arguments' => array(1),
    'access callback' => '_quickpay_callback_access',
  );
  $items['admin/config/system/quickpay'] = array(
    'title' => 'Quickpay configuration',
    'description' => 'Settings for the Quickpay integration',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_quickpay_configuration_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'quickpay.forms.inc',
  );
  return $items;
}

/**
 * Get a payment form.
 *
 * @param $form
 * @param $form_state
 * @param $parameters
 *   A array of parameters:
 *   - order_id (required)
 *   - currency (required)
 *   - amount (required)
 *   - continue_url (required)
 *   - cancel_url (required)
 *   - custom_variables
 *
 * @return mixed
 *
 * @throws \QuickpayException
 */
function quickpay_payment_form($form, &$form_state, $parameters) {
  $helper = new QuickpayHelper();
  // Start by checking parameters.
  $helper->checkParameters($parameters);
  // Build the form.
  $form['#method'] = 'POST';
  $form['#action'] = 'https://payment.quickpay.net';
  // Required variables.
  $data['version'] = QUICKPAY_VERSION;
  $data['merchant_id'] = variable_get('quickpay_merchant_id', '');
  $data['agreement_id'] = variable_get('quickpay_agreement_id', '');
  $data['order_id'] = $parameters['order_id'];
  // Ensure that Order number is at least 4 characters. Else Quickpay will
  // reject the request.
  if (strlen($data['order_id']) < 4) {
    $order_prefix = variable_get('quickpay_order_prefix', '');
    $data['order_id'] = $order_prefix . substr('0000' . $parameters['order_id'], -4 + strlen($order_prefix));
  }
  $currency_info = $helper->currencyInfo($parameters['currency']);
  $data['amount'] = $helper->wireAmount($parameters['amount'], $currency_info);
  $data['currency'] = $currency_info['code'];
  $data['continueurl'] = $parameters['continue_url'];
  $data['cancelurl'] = $parameters['cancel_url'];
  $data['callbackurl'] = url('quickpay/' . $parameters['order_id'], array('absolute' => TRUE));
  // Set the optional variables.
  $data['language'] = $helper->getLanguage();
  $data['autocapture'] = variable_get('quickpay_autocapture', FALSE) ? 1 : 0;
  $data['payment_methods'] = $helper->getPaymentMethods();
  $data['autofee'] = variable_get('quickpay_autofee', FALSE) ? 1 : 0;
  // Add any custom fields.
  if (isset($parameters['custom_variables']) && is_array($parameters['custom_variables'])) {
    foreach ($parameters['custom_variables'] as $key => $value) {
      $data['variables[' . $key . ']'] = $value;
    }
  }
  // Build the checksum.
  $data['checksum'] = $helper->getChecksum($data);
  // Add all data elements as hidden input fields.
  foreach ($data as $name => $value) {
    $form[$name] = array('#type' => 'hidden', '#value' => $value);
  }
  $form['submit'] = array(
    '#id' => 'quickpay-submit-button',
    '#type' => 'submit',
    '#value' => t('Continue to QuickPay'),
  );
  return $form;
}

/**
 * Access callback for callback route.
 *
 * @return bool
 */
function _quickpay_callback_access() {
  $helper = new QuickpayHelper();
  $checksum_calculated = $helper->getChecksumFromRequest();
  $checksum_requested = $_SERVER['HTTP_QUICKPAY_CHECKSUM_SHA256'];
  if (!empty($checksum_requested) && strcmp($checksum_calculated, $checksum_requested) === 0) {
    return TRUE;
  }
  watchdog('quickpay', 'Computed checksum does not match header checksum.', WATCHDOG_ERROR);
  return FALSE;
}

/**
 * The callback for the callback.
 *
 * @param string $order_id
 *   The order ID for the transaction.
 */
function _quickpay_callback($order_id) {
  $request_body = file_get_contents("php://input");
  $request = json_decode($request_body);
  $transaction = new QuickpayTransaction($request);
  foreach (module_implements('quickpay_callback') as $module) {
    $function = $module . '_quickpay_callback';
    $function($order_id, $transaction);
  }
}
