<?php
/**
 * @file
 * Module for testing/debugging the Quickpay payment window.
 */

/**
 * Implements hook_menu().
 */
function quickpay_example_menu() {
  $items = array();
  $items['quickpay_example/checkout'] = array(
    'title' => 'Quickpay Example checkout',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('_quickpay_example_checkout_form'),
    'access callback' => TRUE,
  );
  $items['quickpay_example/success'] = array(
    'title' => 'Quickpay Example success',
    'page callback' => '_quickpay_example_success',
    'access callback' => TRUE,
  );
  $items['quickpay_example/status'] = array(
    'title' => 'Quickpay Example status',
    'page callback' => '_quickpay_example_status',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * The example checkout form.
 *
 * @param $form
 * @param $form_state
 *
 * @return array
 */
function _quickpay_example_checkout_form($form, &$form_state) {
  $parameters = [
    'order_id' => time(),
    'amount' => 1,
    'currency' => 'DKK',
    'continue_url' => url('quickpay_example/success', array('absolute' => TRUE)),
    'cancel_url' => url('quickpay_example/checkout', array('absolute' => TRUE)),
  ];

  return drupal_get_form('quickpay_payment_form', $parameters);
}

/**
 * Content for the success page.
 *
 * @return array
 *   A renderable array.
 */
function _quickpay_example_success() {
  return array(
    '#type' => 'markup',
    '#markup' => '<h1>Congratulations</h1><p>You just completed a purchase.</p>',
  );
}

/**
 * Content for the status page.
 *
 * @return array
 *   A renderable array.
 */
function _quickpay_example_status() {
  $latest_transaction_id = variable_get('quickpay_example_latest_transaction', FALSE);
  if ($latest_transaction_id) {
    $transaction = new QuickpayTransaction($latest_transaction_id);
    $message = 'Approved: ' . ($transaction->approved ? 'TRUE' : 'FALSE') . '</p><p>Message: ' . $transaction->qp_status_msg;
  }
  else {
    $message = 'Transaction has not been completed.';
  }
  return array(
    '#type' => 'markup',
    '#markup' => '<p>' . $message . '</p>',
  );
}

/**
 * Implements hook_quickpay_callback().
 *
 * @param string $order_id
 * @param \QuickpayTransaction $transaction
 */
function quickpay_example_quickpay_callback($order_id, $transaction) {
  if ($transaction->approved) {
    variable_set('quickpay_example_latest_transaction', $transaction->id);
    watchdog('quickpay_example', 'Transaction approved for order ID: !id', array('!id' => $order_id));
  }
  else {
    watchdog('quickpay_example', 'Transaction not approved for order ID: !id', array('!id' => $order_id));
  }
}
